const availableLayers = [
  {
    title: 'Aerial Bing Map With Labels',
    type: 'raster',
    source: 'BingMaps',
    projection: 'EPSG:3857',
    imagerySet: 'AerialWithLabelsOnDemand',
    isActive: true,
    isVisible: true,
    styleUrl: '',
  },
  {
    title: 'Aerial Bing Map',
    type: 'raster',
    source: 'BingMaps',
    projection: 'EPSG:3857',
    imagerySet: 'Aerial',
    isActive: false,
    isVisible: false,
    styleUrl: '',
  },
  {
    title: 'Canvas Dark Bing Map',
    type: 'raster',
    source: 'BingMaps',
    projection: 'EPSG:3857',
    imagerySet: 'CanvasDark',
    isActive: false,
    isVisible: false,
    styleUrl: '',
  },
  {
    title: 'Road On Demand Bing Map',
    type: 'raster',
    source: 'BingMaps',
    projection: 'EPSG:3857',
    imagerySet: 'RoadOnDemand',
    isActive: false,
    isVisible: false,
    styleUrl: '',
  },
  {
    title: 'Open Streets Map',
    type: 'raster',
    source: 'OSM',
    projection: 'EPSG:3857',
    imagerySet: '',
    isActive: false,
    isVisible: false,
    styleUrl: '',
  },
  {
    title: 'MapTiler Satellite Hybrid Vector',
    type: 'vector',
    source: 'MapTilerVector',
    projection: 'EPSG:3857',
    imagerySet: '',
    isActive: false,
    isVisible: false,
    styleUrl: 'https://api.maptiler.com/maps/hybrid/style.json?key=',
  },
  {
    title: 'MapTiler Ocean Vector',
    type: 'vector',
    source: 'MapTilerVector',
    projection: 'EPSG:3857',
    imagerySet: '',
    isActive: false,
    isVisible: false,
    styleUrl: 'https://api.maptiler.com/maps/ocean/style.json?key=',
  },
  {
    title: 'MapTiler Topographic V2 Vector',
    type: 'vector',
    source: 'MapTilerVector',
    projection: 'EPSG:3857',
    imagerySet: '',
    isActive: false,
    isVisible: false,
    styleUrl: 'https://api.maptiler.com/maps/topo-v2/style.json?key=',
  },
  {
    title: 'MapTiler Satellite Hybrid Raster',
    type: 'raster',
    source: 'MapTiler',
    projection: 'EPSG:3857',
    imagerySet: '',
    isActive: false,
    isVisible: false,
    styleUrl: 'https://api.maptiler.com/maps/hybrid/{z}/{x}/{y}.jpg?key=',
  },
  {
    title: 'MapTiler Topographic V2 Raster',
    type: 'raster',
    source: 'MapTiler',
    projection: 'EPSG:3857',
    imagerySet: '',
    isActive: false,
    isVisible: false,
    styleUrl: 'https://api.maptiler.com/maps/topo-v2/{z}/{x}/{y}.png?key=',
  },
  {
    title: 'MapTiler Streets Raster',
    type: 'raster',
    source: 'MapTiler',
    projection: 'EPSG:3857',
    imagerySet: '',
    isActive: false,
    isVisible: false,
    styleUrl: 'https://api.maptiler.com/maps/streets-v2/{z}/{x}/{y}.png?key=',
  },
  {
    title: 'MapTiler Streets Vector',
    type: 'vector',
    source: 'MapTilerVector',
    projection: 'EPSG:3857',
    imagerySet: '',
    isActive: false,
    isVisible: false,
    styleUrl: 'https://api.maptiler.com/maps/streets-v2/style.json?key=',
  },
];

export default availableLayers;
